development:
  cloud_name: dkubcvfjr
  api_key: '452275866764872'
  api_secret: 018LX7U6dOQHkM2NUoIu6X0zoP4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dkubcvfjr
  api_key: '452275866764872'
  api_secret: 018LX7U6dOQHkM2NUoIu6X0zoP4
  enhance_image_tag: true
  static_image_support: false
test:
  cloud_name: dkubcvfjr
  api_key: '452275866764872'
  api_secret: 018LX7U6dOQHkM2NUoIu6X0zoP4
  enhance_image_tag: true
  static_image_support: false
